### PR TITLE
Fixing exported URL's in API and Web

### PR DESCRIPTION
**Pull request by bryannbarbosa**

### CODE REVIEW

**Comment by phroggyy** [comment]
What’s the difference between this and #5?

**Comment by bryannbarbosa** [comment]
This have all revision of main code, with better control and functionality of web and api flag options.
By Default, the command:

**php artisan laraman:export**

He will return **all routes**, web and api, by default, in contrast with old code.

Other implementation is the URL fix, while i was testing the api routes in postman, i found an error in format of url, like this:

**http://localhost/:8000/api/**

**There is a slash after localhost**, this new code **remove this slash**.

The **final result** is: http://localhost:8000/api/

In Web routes, specific in the **main route**: '/', i found the same problem: **http://localhost/:8000**
If a route is a main route, then the URI will be null, with this problem fixed, you have the follow result:
**http://localhost:8000**

**Comment by bryannbarbosa** [comment]
I also test didatic method's in documentation,  for a better understanding on the part of others.

**Comment by phroggyy** [comment]
@bryannbarbosa will this support *all* routes now (even ones not in web/api middleware)?

**Comment by bryannbarbosa** [comment]
@phroggyy Not yet, in those days I'm thinking the best approach to deal with this, I thought of analyzing all the available middlewares in the routes and verifying if it has some traces of api orweb or specifies a specific pattern, it will be a kind of regex, taking all routes by beating that pattern, be it api, web or other specified pattern.

If no pattern is specified, then it catches up absolutely everything, what do you think?

**Pull request closed without merging**
