### PR TITLE
documentation and better code for default usage

### PR DESCRIPTION
**Pull request by bryannbarbosa**
This code is better because you can now use the default command to export all routes and also use flags to specify the route types.

### CODE REVIEW

**Comment by phroggyy** [comment]
API and web does not mean all routes. You’d have to loop over all routes registered. Plenty of people will override and remove one of or both default middleware groups

**Comment by bryannbarbosa** [comment]
can you add me on facebook to talk?
https://www.facebook.com/bryannalvesbarbosa

**Comment by phroggyy** [comment]
I feel like it’d be more beneficial to keep the conversation stored and public

**Comment by bryannbarbosa** [comment]
It's true

**Pull request closed without merging**
